### ISSUE TITLE
Command-line interface

### ISSUE THREAD

**Issue by chonuchan** [dlenski/python-zxing#11]
Hi may I ask how to install the Command-line interface?(for Linux) The package is otherwise working fine in Python 3.5. Thank you.

**Comment by dlenski** [comment]
Did `pip3 install zxing` not do it?

**Comment by chonuchan** [comment]
Thanks for your reply. 
yes, I used "pip3.5 install zxing" to install this package. 
If I type zxing in command line, it returns:
bash: zxing: command not found

**Comment by chonuchan** [comment]
Thanks! indeed my ~/.local/bin is not in $PATH (but this is what I intended). 

Solved by sudo cp ~/.local/bin/zxing /usr/local/bin
