### ISSUE TITLE
Use jpype for wrapper?

### ISSUE THREAD

**Issue by ArlindNocaj** [dlenski/python-zxing#19]
I have been once creating a wrapper with jpype to zxing.
The great thing would be that we avoid parsing issues.

It also allows you to get the metadata from the zxing barcode Object, eg for PDF_417 barcode.

It would simplify the problem a lot but require jpype as well. 

You can also keep the java runtime warm and rerun things on demand with single requests.

Using jPype one can just use the main lines from CommandLineRunner of zxing. 

Any thoughts on that?

**Comment by dlenski** [comment]
That'd be awesome… would make things much more efficient for batch processing _and_ help solve annoying bugs/platform inconsistencies in the CommandLineRunner (like #17).

I don't have any bandwidth to work on this, but I'd gratefully accept a PR and try to review it quickly. :grin:

**Comment by ArlindNocaj** [comment]
I created a project for direct usage of zxing using jpype for barcode extraction. It also works on pdf documents, see https://github.com/ArlindNocaj/document-barcodes
