### ISSUE TITLE
How to get QR Code version, error correction level, and mask?

### ISSUE THREAD

**Issue by winnie19970218** [dlenski/python-zxing#23]

**Comment by winnie19970218** [comment]
Hello, I didn't see any API can get the QR Code version, error correction level, and mask.

**Comment by dlenski** [comment]
This is a wrapper around the ZXing command-line runner, and it can't extract any information that the ZXing CLR can't show.

> any API can get the QR Code version, error correction level, and mask.

I'm curious: why would you _want_ that information while _reading_ a barcode? The whole point of error correction is to be able to transparently and correctly return the originally-encoded string in the face of variable errors while reading the barcode.

**Comment by winnie19970218** [comment]
I made a verification system, the decoder needs to know that the QR code is generated by my program when decoding, so I add the detailed information of the QR code to the database when generating the QR code. By comparing the information obtained by the decoder with the database, you can know whether the QR code is unverified.
There is a class name called Version.java in [com.google.zxing.qrcode.decoder], this class can get the QR code version.

**Comment by dlenski** [comment]
> I made a verification system, the decoder needs to know that the QR code is generated by my program when decoding, so I add the detailed information of the QR code to the database when generating the QR code. By comparing the information obtained by the decoder with the database, you can know whether the QR code is unverified.

This sounds like it's half [steganography](https://en.wikipedia.org/wiki/Steganography), half [security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity). Altogether, it seems like it will provide no security, but may prevent the QR codes from being decoded reliably. 

The whole point of error correction is that sometimes the QR code will **not** be read back perfectly.

>  There is a class name called Version.java in [com.google.zxing.qrcode.decoder], this class can get the QR code version.

[Per above](https://github.com/dlenski/python-zxing/issues/23#issuecomment-1083346065), you would have to extend the ZXing command-line runner to output this information to allow python-zxing to read it.
