### ISSUE TITLE
Different results from online decoder

### ISSUE THREAD

**Issue by cooperlab** [dlenski/python-zxing#25]
Thank you for making this library.

I have a collection of barcodes that mostly fail to decode with the python wrapper, but that are successfully decoded using the online ZXing resource here: [https://zxing.org/w/decode.jspx](https://zxing.org/w/decode.jspx). Do you have any insights on what options the online decoder might be using, or how this might differ from your wrapper? Happy to share data privately.

**Comment by dlenski** [comment]
> Do you have any insights on what options the online decoder might be using, or how this might differ from your wrapper?

Are you using either AZTEC code or PDF417? I made a couple changes to improve those decoders upstream (see https://github.com/zxing/zxing/commits?author=dlenski), but they aren't yet in a tagged release of ZXing.

Other than that, I don't have any ideas about known deficiencies.

> Happy to share data privately.

I'm definitely interested in seeing them. You can email to the address on my profile.

**Comment by cooperlab** [comment]
We resolved these issues by aggressively augmenting the images. We create a basket of different versions of the image transformed by intensity and thresholded at different gray levels. This brought us to a 98% read rate. I'm closing this since it seems like the decoding library is working fine.
