### ISSUE TITLE
Insufficient handling of missing result in BarCode.__repr__

### ISSUE THREAD

**Issue by stefan6419846** [dlenski/python-zxing#36]
When there is no result for a file, id est we have the standard output

> file:///home/stefan/temp/image-001.png: No barcode found

then displaying the result will fail as `BarCode.__repr__` does not like it:

```python3
Traceback (most recent call last):
  File "/home/stefan/temp/run.py", line 57, in <module>
    print(reader.decode(path))
  File "/home/stefan/temp/venv/lib/python3.9/site-packages/zxing/__init__.py", line 238, in __repr__
    self.__class__.__name__, self.raw, self.parsed, self.raw_bits.hex(),
AttributeError: 'NoneType' object has no attribute 'hex'
```

**Comment by dlenski** [comment]
What version are you using? `zxing --version` should show it, or `python3 -m zxing.__main__ --version` from the build directory.

**Comment by stefan6419846** [comment]
I was using the latest *master* branch due to the broken PyPI builds.
