### ISSUE TITLE
what's the difference between raw and parsed results?

### ISSUE THREAD

**Issue by wantao666** [dlenski/python-zxing#6]
i got the result
 `BarCode(raw='This should be QR_CODE', parsed='This should be QR_CODE', format='QR_CODE', type='TEXT', points=[(15.0, 87.0), (15.0, 15.0), (87.0, 15.0), (75.0, 75.0)])`,
but the row's content the same with the parsed's content.
i don't know the difference.
could you explain the meanings of the raw and the parsed?give an example is best.

**Comment by dlenski** [comment]
>  could you explain the meanings of the raw and the parsed?give an example is best.

It's based entirely on the underlying ZXing library, which offers [various result parsers](https://zxing.github.io/zxing/apidocs/com/google/zxing/client/result/ResultParser.html) to try to understand the structure of the data in barcode text. :man_shrugging: 

For example, the [GeoResultParser](https://zxing.github.io/zxing/apidocs/com/google/zxing/client/result/GeoResultParser.html) will parse `geo:` URIs into latitude, longitude, and elevation:

```
$ qrencode "geo:48.19858,16.37164,171" -o /tmp/test.png
$ zxing /tmp/test.png 
/tmp/test.png
=============
  Decoded GEO barcode in QR_CODE format.
  Raw text:    'geo:48.19858,16.37164,171'
  Parsed text: '48.19858, 16.37164, 171.0m'
```

For general-purpose barcode parsing, you should use the `raw` content. Only use the parsed content if you understand and trust how ZXing parses it, and actually _want_ the parsed format.
