### ISSUE TITLE
Java binary specified does not exist

### ISSUE THREAD

**Issue by Michelangelo-Y** [dlenski/python-zxing#7]
I use "pip install zxing" to install zxing 0.11,and in my venv dir have all the file demand，“core.jar”“javase.jar”“jcommander.jar”，but when run zxing.BarCodeReader().decode(xxx.png) raise error :
"raise BarCodeReaderException("Java binary specified does not exist", self.java, e) zxing.BarCodeReaderException: ('Java binary specified does not exist', 'java', FileNotFoundError(2, '系统找不到指定的文件。', None, 2, None))"

**Comment by dlenski** [comment]
Is the Java binary itself installed, as described in the README?

**Comment by Michelangelo-Y** [comment]
> Is the Java binary itself installed, as described in the README?

thanks，the issue have solved by install jdk，maybe there some errors occurred during the jdk installation process yesterday。
